Repository microcks/microcks, pull requests merged in 2023-11, with the labels that each got.

#959 fix: Remove unused OAuth2ClientContext constructor
  commons/model/src/main/java/io/github/microcks/domain/OAuth2ClientContext.java
Labels: kind/task

#961 Fix non-public properties for SecretRef
  commons/model/src/main/java/io/github/microcks/domain/SecretRef.java
Labels: kind/task

#957 feat: add configuration for Cors origin
  webapp/src/main/java/io/github/microcks/config/WebConfiguration.java
  webapp/src/main/java/io/github/microcks/web/RestController.java
  webapp/src/main/resources/config/application.properties
Labels: component/mocks, kind/enhancement, component/install

#985 fix: add null check to getFileName
  webapp/src/main/java/io/github/microcks/util/GitLabReferenceURLBuilder.java
Labels: kind/bug, component/importer

#962 refactor: Add a private constructor to IdBuilder to hide the implicit public one.
  commons/model/src/main/java/io/github/microcks/util/IdBuilder.java
Labels: kind/task

#996 $ref component not being parsed in json schema causing issue with nullable field
  README.md
  commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java
  commons/util/src/test/java/io/github/microcks/util/openapi/OpenAPISchemaValidatorTest.java
  commons/util/src/test/resources/io/github/microcks/util/openapi/nullable-fields-openapi.yaml
Labels: kind/bug, component/tests

#1002 Allow keycloak-less kubernetes installation
  install/kubernetes/README.md
  install/kubernetes/microcks/templates/NOTES.txt
  install/kubernetes/microcks/templates/claim.yaml
  install/kubernetes/microcks/templates/configmap.yaml
  install/kubernetes/microcks/templates/deployment.yaml
  install/kubernetes/microcks/templates/ingress.yaml
  install/kubernetes/microcks/templates/secret.yaml
  install/kubernetes/microcks/templates/service.yaml
  install/kubernetes/microcks/values.yaml
Labels: kind/feature, component/openshift, component/install, component/kubernetes

#967 feat: kafka login callback handler support
  minions/async/src/main/docker/Dockerfile.legacy-jar
  minions/async/src/main/java/io/github/microcks/minion/async/producer/KafkaProducerManager.java
Labels: kind/feature, component/mocks, component/install

#1003 Revert "feat: kafka login callback handler support"
  minions/async/src/main/docker/Dockerfile.legacy-jar
  minions/async/src/main/java/io/github/microcks/minion/async/producer/KafkaProducerManager.java
Labels: kind/task
