Repository microcks/microcks, pull requests merged in 2023-10, with the labels that each got.

#938 fix: Location override with absolute url
  webapp/src/main/java/io/github/microcks/util/AbsoluteUrlMatcher.java
  webapp/src/main/java/io/github/microcks/web/RestController.java
  webapp/src/test/java/io/github/microcks/util/AbsoluteUrlMatcherTest.java
Labels: component/mocks, kind/enhancement

#940 Replaced Javafaker by Datafaker.
  commons/util-el/pom.xml
  commons/util-el/src/main/java/io/github/microcks/util/el/function/FakerELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomCityELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomCountryCodeELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomCountryELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomEmailELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomFirstNameELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomFullNameELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomLastNameELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomLatitudeELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomLongitudeELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomNamePrefixELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomNameSuffixELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomPhoneNumberELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomStreetAddressELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomStreetNameELFunction.java
Labels: kind/task, component/mocks, kind/enhancement

#947 Reduce some sonar cloud issue and add dev sh
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomBooleanELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomIntELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomStringELFunction.java
  commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomValueELFunction.java
  dev/start-keycloak-docker.sh
  dev/start-keycloak-podman.sh
  dev/start-mongodb-docker.sh
  dev/start-mongodb-podman.sh
  minions/async/src/main/java/io/github/microcks/minion/async/producer/AMQPProducerManager.java
  minions/async/src/main/java/io/github/microcks/minion/async/producer/NATSProducerManager.java
  webapp/src/main/java/io/github/microcks/config/ProxyConfiguration.java
  webapp/src/main/java/io/github/microcks/repository/DailyStatisticRepository.java
  webapp/src/main/java/io/github/microcks/repository/EventMessageRepository.java
  webapp/src/main/java/io/github/microcks/repository/GenericResourceRepository.java
  webapp/src/main/java/io/github/microcks/repository/ImportJobRepository.java
  webapp/src/main/java/io/github/microcks/repository/RequestRepository.java
  webapp/src/main/java/io/github/microcks/repository/ResourceRepository.java
  webapp/src/main/java/io/github/microcks/repository/ResponseRepository.java
  webapp/src/main/java/io/github/microcks/repository/SecretRepository.java
  webapp/src/main/java/io/github/microcks/repository/ServiceRepository.java
  webapp/src/main/java/io/github/microcks/repository/TestConformanceMetricRepository.java
  webapp/src/main/java/io/github/microcks/service/ImportExportService.java
  webapp/src/main/java/io/github/microcks/service/MetricsService.java
  webapp/src/main/java/io/github/microcks/util/HTTPDownloader.java
  webapp/src/main/java/io/github/microcks/util/asyncapi/AsyncAPIImporter.java
Labels: kind/task
