Repository microcks/microcks, pull requests merged in 2024-08, with the labels that each got.

#1264 Prefix named helm templates with microcks
  install/kubernetes/microcks/templates/_helpers.tpl
  install/kubernetes/microcks/templates/deployment.yaml
  install/kubernetes/microcks/templates/secret.yaml
Labels: component/openshift, kind/enhancement, component/install, component/kubernetes

#1267 GraphQL schema instrospection not working on native distribution
  distro/uber/src/main/resources/META-INF/native-image/reflect-config.json
Labels: kind/bug, component/mocks

#1294 Add missing guard on jsonNode schema path access
  commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java
Labels: kind/bug, component/tests
