Repository microcks/microcks, pull requests merged in 2024-04, with the labels that each got.

#1098 feat: Templating rest mock responses' headers
  webapp/src/main/java/io/github/microcks/web/RestController.java
  webapp/src/test/java/io/github/microcks/web/RestControllerIT.java
  webapp/src/test/resources/io/github/microcks/util/openapi/pastry-with-headers-openapi.yaml
Labels: component/mocks, kind/enhancement, keep-open

#1130 Add integration tests to AMQPMessageConsumptionTaskITest class
  minions/async/pom.xml
  minions/async/src/test/java/io/github/microcks/minion/async/consumer/AMQPMessageConsumptionTaskITest.java
Labels: kind/task

#1101 feat: Add proxy support for the rest controller
  webapp/pom.xml
  webapp/src/main/java/io/github/microcks/service/ProxyService.java
  webapp/src/main/java/io/github/microcks/util/DispatchCriteriaHelper.java
  webapp/src/main/java/io/github/microcks/util/DispatchStyles.java
  webapp/src/main/java/io/github/microcks/util/dispatcher/ProxyFallbackSpecification.java
  webapp/src/main/java/io/github/microcks/util/har/HARImporter.java
  webapp/src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java
  webapp/src/main/java/io/github/microcks/util/postman/PostmanCollectionImporter.java
  webapp/src/main/java/io/github/microcks/web/MockControllerCommons.java
  webapp/src/main/java/io/github/microcks/web/RestController.java
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/operation/operation-override.page.html
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/operation/operation-override.page.ts
  webapp/src/test/java/io/github/microcks/web/RestControllerIT.java
  webapp/src/test/resources/io/github/microcks/util/openapi/pastry-for-proxy-openapi.yaml
  webapp/src/test/resources/io/github/microcks/util/openapi/pastry-with-proxy-fallback-openapi.yaml
  webapp/src/test/resources/io/github/microcks/util/openapi/pastry-with-proxy-openapi.yaml
Labels: component/mocks, kind/enhancement

#1141 fix: add a null check before asserting on mediatype of the test http …
  webapp/src/main/java/io/github/microcks/util/openapi/OpenAPITestRunner.java
Labels: kind/bug, component/tests

#1139 Allow JSON pointers to array and object contents in templates
  commons/util-el/src/main/java/io/github/microcks/util/el/VariableReferenceExpression.java
  commons/util-el/src/test/java/io/github/microcks/util/el/VariableReferenceExpressionTest.java
Labels: component/mocks, kind/enhancement

#1135 feat: Add proxy support for the soap controller
  webapp/src/main/java/io/github/microcks/web/MockControllerCommons.java
  webapp/src/main/java/io/github/microcks/web/RestController.java
  webapp/src/main/java/io/github/microcks/web/SoapController.java
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/operation/operation-override.page.ts
  webapp/src/test/java/io/github/microcks/web/AbstractBaseIT.java
  webapp/src/test/java/io/github/microcks/web/RestControllerIT.java
  webapp/src/test/java/io/github/microcks/web/SoapControllerIT.java
  webapp/src/test/resources/io/github/microcks/util/soapui/HelloService-to-set-proxy-soapui-project.xml
  webapp/src/test/resources/io/github/microcks/util/soapui/HelloService-to-test-proxy-soapui-project.xml
Labels: kind/feature, component/mocks

#1144 feat: Add support for object query parameters
  webapp/src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java
  webapp/src/test/java/io/github/microcks/util/openapi/OpenAPIImporterTest.java
  webapp/src/test/resources/io/github/microcks/util/openapi/object-query-params.yaml
Labels: component/mocks, kind/enhancement, component/importer

#1150 Add integration test to UploadArtifactController
  minions/async/src/test/java/io/github/microcks/minion/async/consumer/AMQPMessageConsumptionTaskIT.java
  webapp/src/main/java/io/github/microcks/util/HTTPDownloader.java
  webapp/src/main/java/io/github/microcks/web/UploadArtifactController.java
  webapp/src/test/java/io/github/microcks/web/UploadArtifactControllerIT.java
  webapp/src/test/java/io/github/microcks/web/UploadArtifactControllerTest.java
Labels: kind/task

#1154 Add "select all" & "deselect all" actions for operations list on test create page
  webapp/src/main/webapp/src/app/pages/tests/create/test-create.page.css
  webapp/src/main/webapp/src/app/pages/tests/create/test-create.page.html
  webapp/src/main/webapp/src/app/pages/tests/create/test-create.page.ts
  webapp/src/main/webapp/src/app/pages/tests/create/tests.page.spec.ts
Labels: component/ux, kind/enhancement
