Repository microcks/microcks, pull requests merged in 2024-01, with the labels that each got.

#1025 Optimize: Extract Tabset in service view into another component and render only the selected tab
  webapp/src/main/webapp/src/app/app.module.ts
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.html
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.ts
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.html
Labels: component/ux, kind/enhancement

#1027 feat: add auto-cors
  webapp/src/main/java/io/github/microcks/config/WebConfiguration.java
  webapp/src/main/java/io/github/microcks/web/filter/DynamicOriginCorsFilter.java
Labels: component/mocks, kind/enhancement

#1041 Adding full observability with Opentelemetry to microcks
  benchmark/README.md
  benchmark/bench-microcks.js
  observability/configs/grafana-datasources.yaml
  observability/configs/otel-collector.yaml
  observability/configs/tempo.yaml
  observability/dashboards/dashboards.yml
  observability/dashboards/k6.json
  observability/dashboards/microcks-overview.json
  observability/start-o11y-dev-stack.sh
  observability/teardown-o11y-dev-stack.sh
  webapp/pom.xml
  webapp/src/main/docker/Dockerfile
  webapp/src/main/java/io/github/microcks/config/MicrometerConfiguration.java
  webapp/src/main/resources/config/application.properties
Labels: kind/feature, component/install

#1049 fix(#1016): support for query params array
  webapp/src/main/java/io/github/microcks/util/DispatchCriteriaHelper.java
  webapp/src/main/java/io/github/microcks/util/URIBuilder.java
  webapp/src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java
  webapp/src/test/java/io/github/microcks/util/DispatchCriteriaHelperTest.java
  webapp/src/test/java/io/github/microcks/util/URIBuilderTest.java
Labels: kind/bug, component/mocks, component/importer

#1051 feature(helm-Chart): Added the possibility of using a secret with a keystore
  install/kubernetes/microcks/README.md
  install/kubernetes/microcks/templates/deployment.yaml
  install/kubernetes/microcks/values.yaml
Labels: component/openshift, kind/enhancement, component/install, component/kubernetes
