Repository microcks/microcks, pull requests merged in 2025-04, with the labels that each got.

#1552 feat: add installation script for [podman|docker]-compose
  install/docker-compose/async-addon.yml
  install/podman-compose/async-addon.yml
  install/podman-compose/podman-compose-devmode.yml
  install/podman-compose/podman-compose.yml
  testsuite/install-compose.sh
Labels: kind/enhancement, component/install, type/Part, component/build

#1544 feat: add workflow for testing sample APIs
  benchmark/bench-microcks.js
  testsuite/api-tests.js
  testsuite/commons.js
Labels: component/ux, kind/enhancement, component/install, type/Part, component/build

#1570 feat: add config for healthcheck workflow
  .github/workflows/microcks-health-check.yml
Labels: kind/feature, component/ux, component/install, type/Part, component/build

#1580 feat: cover helm in check-health script
  testsuite/check-health.sh
Labels: component/ux, kind/enhancement, component/install, type/Part, component/kubernetes, component/build

#1579 fix(search_field): fix the dropdown bug when no domain mention in entries
  webapp/src/main/webapp/src/app/pages/services/services.page.ts
Labels: component/ux, kind/enhancement

#1586 fix: ui alignment for dropdown
  webapp/src/main/webapp/src/styles.css
Labels: component/ux, kind/regression
