Repository microcks/microcks, pull requests merged in 2025-10, with the labels that each got.

#1765 fix: swagger import fail because body parameter is not exist
  commons/model/src/main/java/io/github/microcks/domain/ParameterLocation.java
  webapp/src/main/webapp/src/app/models/service.model.ts
  webapp/src/test/java/io/github/microcks/util/openapi/SwaggerImporterTest.java
Labels: kind/bug, component/api, kind/enhancement, component/importer, java

#1768 chore: removed unused import in HttpHeadersStringToStringsMap.java
  webapp/src/main/java/io/github/microcks/util/script/HttpHeadersStringToStringsMap.java
Labels: kind/task, java

#1766 Feat/add live traces component
  webapp/src/main/java/io/github/microcks/web/TracingController.java
  webapp/src/main/webapp/src/app/app.routes.ts
  webapp/src/main/webapp/src/app/components/live-traces/live-traces.component.css
  webapp/src/main/webapp/src/app/components/live-traces/live-traces.component.html
  webapp/src/main/webapp/src/app/components/live-traces/live-traces.component.ts
  webapp/src/main/webapp/src/app/components/live-traces/trace-group-list/trace-group-list.component.css
  webapp/src/main/webapp/src/app/components/live-traces/trace-group-list/trace-group-list.component.html
  webapp/src/main/webapp/src/app/components/live-traces/trace-group-list/trace-group-list.component.ts
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/operation/operation-override.page.html
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/operation/operation-override.page.ts
  webapp/src/main/webapp/src/app/services/tracing.service.ts
  webapp/src/main/webapp/src/app/utils/trace-utils.ts
  webapp/src/main/webapp/src/styles.css
Labels: kind/feature, component/mocks, component/ux, type/Part

#1772 Feat/add explain event to rest invocation processor
  webapp/src/main/java/io/github/microcks/util/tracing/CommonEvents.java
  webapp/src/main/java/io/github/microcks/web/RestInvocationProcessor.java
Labels: kind/feature, component/mocks, type/Part

#1770 feat: add live traces component to service detail
  webapp/src/main/webapp/src/app/components/collapsible-live-traces/collapsible-live-traces.component.css
  webapp/src/main/webapp/src/app/components/collapsible-live-traces/collapsible-live-traces.component.html
  webapp/src/main/webapp/src/app/components/collapsible-live-traces/collapsible-live-traces.component.ts
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.css
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.html
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.css
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.html
  webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.ts
Labels: kind/feature, component/mocks, component/ux, type/Part
