Repository microcks/microcks, pull requests merged in 2025-09, with the labels that each got.

#1674 Refactor/Enchance Dialog Upload Component to have better UX
  webapp/src/main/webapp/src/app/app.component.html
  webapp/src/main/webapp/src/app/app.component.ts
  webapp/src/main/webapp/src/app/components/drag-drop-overlay/drag-drop-overlay.component.css
  webapp/src/main/webapp/src/app/components/drag-drop-overlay/drag-drop-overlay.component.html
  webapp/src/main/webapp/src/app/components/drag-drop-overlay/drag-drop-overlay.component.ts
  webapp/src/main/webapp/src/app/components/uploader-dialog/quick-import-dialog.component.css
  webapp/src/main/webapp/src/app/components/uploader-dialog/quick-import-dialog.component.html
  webapp/src/main/webapp/src/app/components/uploader-dialog/quick-import-dialog.component.ts
  webapp/src/main/webapp/src/app/components/uploader-dialog/tabs/download/quick-import-download-tab.component.css
  webapp/src/main/webapp/src/app/components/uploader-dialog/tabs/download/quick-import-download-tab.component.html
  webapp/src/main/webapp/src/app/components/uploader-dialog/tabs/download/quick-import-download-tab.component.ts
  webapp/src/main/webapp/src/app/components/uploader-dialog/tabs/upload/quick-import-upload-tab.component.css
  webapp/src/main/webapp/src/app/components/uploader-dialog/tabs/upload/quick-import-upload-tab.component.html
  webapp/src/main/webapp/src/app/components/uploader-dialog/tabs/upload/quick-import-upload-tab.component.ts
  webapp/src/main/webapp/src/app/components/vertical-nav/vertical-nav.component.html
  webapp/src/main/webapp/src/app/components/vertical-nav/vertical-nav.component.ts
  webapp/src/main/webapp/src/app/pages/importers/_components/uploader.dialog.css
  webapp/src/main/webapp/src/app/pages/importers/_components/uploader.dialog.html
  webapp/src/main/webapp/src/app/pages/importers/_components/uploader.dialog.ts
  webapp/src/main/webapp/src/app/pages/importers/importers.page.ts
  webapp/src/main/webapp/src/app/pages/services/services.page.html
  webapp/src/main/webapp/src/app/pages/services/services.page.ts
  webapp/src/main/webapp/src/app/services/drag-drop.service.ts
  webapp/src/main/webapp/src/app/services/uploader-dialog.service.ts
  webapp/src/main/webapp/src/styles.css
Labels: kind/feature, component/ux, kind/enhancement

#1697 feat: more principled JS fetch and tests
  webapp/src/main/java/io/github/microcks/util/script/JsScriptEngineBinder.java
  webapp/src/test/java/io/github/microcks/util/script/JsScriptEngineBinderTest.java
  webapp/src/test/java/io/github/microcks/util/script/TestFetchController.java
Labels: kind/task, component/mocks, component/build

#1732 Refactor ProtobufImporter & MockRequest: Reduce Sonar-reported Cognitive Complexity (Resolves #1714)
  webapp/src/main/java/io/github/microcks/util/grpc/ProtobufImporter.java
  webapp/src/main/java/io/github/microcks/util/script/MockRequest.java
Labels: kind/task, java

#1752 feat: add basic tracing storage and query
  webapp/src/main/java/io/github/microcks/config/OtelAutoConfigurationCustomizerProvider.java
  webapp/src/main/java/io/github/microcks/service/SpanStorageService.java
  webapp/src/main/java/io/github/microcks/util/otel/CustomExplainTraceProcessor.java
  webapp/src/main/java/io/github/microcks/util/tracing/CommonEvents.java
  webapp/src/main/java/io/github/microcks/util/tracing/TraceUtil.java
  webapp/src/main/java/io/github/microcks/web/RestController.java
  webapp/src/main/java/io/github/microcks/web/RestInvocationProcessor.java
  webapp/src/main/java/io/github/microcks/web/TracingController.java
  webapp/src/test/java/io/github/microcks/service/SpanStorageServiceTest.java
  webapp/src/test/java/io/github/microcks/util/TraceUtilTest.java
  webapp/src/test/java/io/github/microcks/util/otel/CustomExplainTraceProcessorTest.java
  webapp/src/test/java/io/github/microcks/web/TracingControllerIT.java
Labels: kind/feature, component/mocks, component/ux, component/api, type/Part

#1754 Feat/add sse endpoint
  webapp/src/main/java/io/github/microcks/event/TraceEvent.java
  webapp/src/main/java/io/github/microcks/service/SpanStorageService.java
  webapp/src/main/java/io/github/microcks/util/tracing/SpanFilterUtil.java
  webapp/src/main/java/io/github/microcks/web/TraceSubscriptionManager.java
  webapp/src/main/java/io/github/microcks/web/TracingController.java
  webapp/src/test/java/io/github/microcks/service/SpanStorageServiceTest.java
  webapp/src/test/java/io/github/microcks/util/tracing/SpanFilterUtilTest.java
  webapp/src/test/java/io/github/microcks/web/TraceSubscriptionManagerTest.java
  webapp/src/test/java/io/github/microcks/web/TracingControllerIT.java
Labels: kind/feature, component/mocks, component/ux, component/api, type/Part
